---
version: 3
jobs:
    create-instances:
        docker:
            - image: codaprotocol/coda-automation:manual
              environment:
                TESTNET: smoke_test
        steps:
            - checkout
            - run:
                  name: terraform init
                  command: cd terraform/testnets/testnet-smoke-test && terraform init
            - run:
                  name: terraform refresh
                  command: cd terraform/testnets/testnet-smoke-test && terraform refresh
            - run:
                  name: terraform plan
                  command: cd terraform/testnets/testnet-smoke-test && terraform plan
            - run:
                  name: terraform apply -auto-approve
                  command: cd terraform/testnets/testnet-smoke-test && terraform apply -auto-approve
            - run:
                  name: ssh config
                  command: |
                    echo -e "$TESTNETPEM" > ~/.ssh/id_rsa
                    chmod 0600 ~/.ssh/id_rsa
                    echo -e "Host *.amazonaws.com\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n  User admin" > ~/.ssh/config
            - run:
                  name: ansible init
                  command: cd ansible && ./play coda-init.yaml




workflows:
    version: 2
    smoke-test:
        jobs:
            - create-instances
