---
version: 3
jobs:
    create-instances:
        docker:
            - image: codaprotocol/coda-automation:latest
        steps:
            - checkout
            - run:
                  name: terraform init
                  command: cd terraform/testnets/testnet-smoke-test && terraform init
            - run:
                  name: terraform refresh
                  command: cd terraform/testnets/testnet-smoke-test && terraform refresh
            - run:
                  name: terraform plan
                  command: cd terraform/testnets/testnet-smoke-test && terraform plan
            - run:
                  name: terraform apply -auto-approve
                  command: cd terraform/testnets/testnet-smoke-test && terraform apply -auto-approve



workflows:
    version: 2
    smoke-test:
        jobs:
            - create-instances
