apiVersion: apps/v1
kind: Deployment
metadata:
  name: fish-block-producer-1
  labels:
    app: fish-block-producer-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fish-block-producer-1
  template:
    metadata:
      labels:
        app: fish-block-producer-1
        testnet: bugspray
        role: block-producer
        class: fish
        version: 0.0.12-beta-release-0.0.13-beta-7cee1ba
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      - name: fix-perms
        image: busybox
        command:
        - sh
        - -c
        - for dir in keys echo-keys faucet-keys; do [ -d /$dir ] && /bin/cp /$dir/* /wallet-keys; done; /bin/chmod 0700 /wallet-keys
        volumeMounts:
        - name: private-keys
          mountPath: "/keys/"
          readOnly: true
        
        - name: echo-service-key
          mountPath: "/echo-keys/"
          readOnly: true
        - name: faucet-service-key
          mountPath: "/faucet-keys/"
          readOnly: true
        - name: wallet-keys
          mountPath: /wallet-keys
        securityContext:
          runAsUser: 0
      - name: install-key
        image: codaprotocol/coda-daemon:0.0.12-beta-release-0.0.13-beta-7cee1ba
        command:
        - bash
        - -c
        - for key in key echo-key faucet-key; do [ ! -f /root/wallet-keys/$key ] || coda accounts import -config-directory /root/.coda-config -privkey-path /root/wallet-keys/$key; done
        volumeMounts:
        - name: wallet-keys
          mountPath: /root/wallet-keys
        - name: config-dir
          mountPath: /root/.coda-config
        env: 
          - name: CODA_PRIVKEY_PASS
            value: "naughty blue worm" 
      containers:
      
      - name: user-agent
        resources:
          requests:
            memory: 512m
            cpu: 0.1
        image: codaprotocol/coda-user-agent:0.1.5-bugspray
        command: ["bash"]
        args: ["-c", "python3 agent.py", ]
        env: 
          - name: AGENT_SEND_EVERY_MINUTES
            value: "10"
          - name: CODA_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: online-fish-account-1-key
                key: pub
          - name: CODA_PRIVKEY_PASS
            value: "naughty blue worm"
          - name: PYTHONUNBUFFERED
            value: "1"
        ports: 
          - name: metrics
            containerPort: 8000
        imagePullPolicy: Always
      
      - name: bots
        resources:
          requests:
            memory: 512m
            cpu: 0.1
        image: codaprotocol/coda-bots:0.0.13-beta-1
        env:
          - name: CODA_GRAPHQL_HOST
            value: "0.0.0.0"
          - name: CODA_GRAPHQL_PORT
            value: "3085"
          - name: ECHO_PUBLICKEY
            valueFrom:
              secretKeyRef:
                name: echo-service-key
                key: pub
          - name: ECHO_PASSWORD
            value: "naughty blue worm"
          - name: FAUCET_PUBLICKEY
            valueFrom:
              secretKeyRef:
                name: faucet-service-key
                key: pub
          - name: FAUCET_PASSWORD
            value: "naughty blue worm"
          - name: DISCORD_API_KEY
            valueFrom:
              secretKeyRef:
                name: o1-discord-api-key
                key: o1discord
          - name: FAUCET_AMOUNT
            value: "10000000000"
          - name: FEE_AMOUNT
            value: "100000000"
        imagePullPolicy: Always
      - name: coda
        resources:
          limits:
            memory: 6.0Gi
          requests:
            memory: 2.0Gi
            cpu: 1
        image: codaprotocol/coda-daemon:0.0.12-beta-release-0.0.13-beta-7cee1ba
        command: ["/usr/bin/dumb-init", "/root/init_coda.sh"]
        args: [ "daemon",
          "-log-level", "Trace",
          "-log-json",
          "-config-directory", "/root/.coda-config",
          "-client-port", "$(DAEMON_CLIENT_PORT)",
          "-rest-port", "$(DAEMON_REST_PORT)",
          "-insecure-rest-server",
          "-external-port", "$(DAEMON_EXTERNAL_PORT)",
          "-metrics-port", "$(DAEMON_METRICS_PORT)",
          "-block-producer-key", "/root/wallet-keys/key",
          "-peer", "/ip4/104.196.195.165/tcp/10001/ipfs/12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr",
          "-peer", "/ip4/35.196.112.167/tcp/10001/ipfs/12D3KooWB79AmjiywL1kMGeKHizFNQE9naThM2ooHgwFcUzt6Yt1",
        ]
        env:
          - name: DAEMON_REST_PORT
            value: "3085"
          - name: DAEMON_CLIENT_PORT
            value: "8301"
          - name: DAEMON_METRICS_PORT
            value: "10000"
          - name: DAEMON_EXTERNAL_PORT
            value: "10006"
          - name: CODA_PRIVKEY_PASS
            value: "naughty blue worm"
        ports:
          - containerPort: 10006
            hostPort: 10006
            protocol: TCP
          - name: graphql
            containerPort: 3085
          - name: metrics
            containerPort: 10000
        imagePullPolicy: Always
        volumeMounts:
        - name: wallet-keys
          mountPath: /root/wallet-keys
        - name: config-dir
          mountPath: /root/.coda-config
      volumes:
      - name: private-keys
        secret:
          secretName: online-fish-account-1-key
          defaultMode: 256
          items:
          - key: key
            path: key
          - key: pub
            path: key.pub
      
      - name: echo-service-key
        secret:
          secretName: echo-service-key
          defaultMode: 256
          items:
          - key: key
            path: echo-key
          - key: pub
            path: echo-key.pub
      - name: faucet-service-key
        secret:
          secretName: faucet-service-key
          defaultMode: 256
          items:
          - key: key
            path: faucet-key
          - key: pub
            path: faucet-key.pub
      - name: wallet-keys
        emptyDir: {}
      - name: config-dir
        emptyDir: {}
