
# task to install and configure filebeat-oss

- name: Add apt signing key
  become: true
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Apt repository
  become: true
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main
    state: present
    filename: elastic-7.x.list

- name: Install package
  become: true
  apt:
    name: filebeat=7.3.2
    state: present
    update_cache: yes
  register: apt_status
  until: apt_status|success
  delay: 6
  retries: 10

- name: Copy Filebeat Config
  become: true
  copy:
    dest: /etc/filebeat/filebeat.yml
    content: |
        setup.ilm.enabled: false
        logging.level: error
        filebeat.inputs:
        - type: log
          enabled: true
          json.keys_under_root: true
          json.add_error_key: true
          json.overwrite_keys: true
          overwrite_keys: true
          paths:
            - /home/admin/test-*/*.log
            - /home/admin/test-*/*.log.*

        output.elasticsearch:
          hosts:
            - "{{ elastic_url }}"
          protocol: "https"


- name: force systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: Start filebeat
  become: true
  systemd:
    state: restarted
    name: filebeat
