# FIXME: run_once doesn't work in free

- name: "get proving url from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id 'testnet/proving/s3_url'"
  register: proving_url
  delegate_to: 127.0.0.1
- set_fact:
    proving_url: "{{ proving_url.stdout | from_json | json_query('SecretString')  }}"

- name: "get elasticsearch endpoint from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id {{'testnet/' + netname + '/elasticsearch/endpoint'}}"
  register: elasticsearch_endpoint
  delegate_to: 127.0.0.1
- set_fact:
    elasticsearch_endpoint: "{{ elasticsearch_endpoint.stdout | from_json | json_query('SecretString')  }}"

- name: "get kibana endpoint from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id {{'testnet/' + netname + '/kibana/endpoint'}}"
  register: kibana_endpoint
  delegate_to: 127.0.0.1
- set_fact:
    kibana_endpoint: "{{ kibana_endpoint.stdout | from_json | json_query('SecretString')  }}"
