- name: "get proving url from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id 'testnet/proving/s3_url'"
  register: proving_url
  delegate_to: 127.0.0.1
- set_fact:
    proving_url: "{{ proving_url.stdout | from_json | json_query('SecretString') }}"

- name: "get grafana api info from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id 'testnet/grafanstack'"
  register: grafanstack
  delegate_to: 127.0.0.1
- set_fact:
    grafanastack_data: "{{ grafanstack.stdout | from_json | json_query('SecretString') }}"
- set_fact:
    grafana_graphite_api: "{{ grafanastack_data.graphite_writer }}"

- name: "get elasticsearch endpoint from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id 'testnet/elasticstack'"
  register: elasticstack
  delegate_to: 127.0.0.1

- set_fact:
    elasticstack_data: " {{ elasticstack.stdout | from_json | json_query('SecretString')}} "

# - debug:
#    msg: elasticstack_data == {{ elasticstack_data }}

# FIXME: See grafana dictionary method above (not nested json)
- set_fact:
    elastic_url: "{{ elasticstack_data | from_json | json_query('elastic') }}"
- set_fact:
    kibana_url:  "{{ elasticstack_data | from_json | json_query('kibana') }}"

- name: "get testnet keys from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id 'testnet/testkeys'"
  register: proverkeys
  delegate_to: 127.0.0.1

- set_fact:
    key_data: " {{ proverkeys.stdout | from_json | json_query('SecretString') }} "

# - debug:
#     msg: key_data == {{ key_data }}

- set_fact:
    privkey_pass:  "{{ key_data | from_json | json_query('privkey_pass') }}"

# - debug:
#     msg: privkey_pass == {{ privkey_pass }}

- set_fact:
    privkey_0:  "{{ key_data | from_json | json_query('privkey_0') }}"
- set_fact:
    pubkey_0:  "{{ key_data | from_json | json_query('pubkey_0') }}"

- set_fact:
    privkey_1:  "{{ key_data | from_json | json_query('privkey_1') }}"
- set_fact:
    pubkey_1:  "{{ key_data | from_json | json_query('pubkey_1') }}"

- set_fact:
    privkey_2:  "{{ key_data | from_json | json_query('privkey_2') }}"
- set_fact:
    pubkey_2:  "{{ key_data | from_json | json_query('pubkey_2') }}"

- set_fact:
    privkey_3:  "{{ key_data | from_json | json_query('privkey_3') }}"
- set_fact:
    pubkey_3:  "{{ key_data | from_json | json_query('pubkey_3') }}"

- set_fact:
    privkey_4:  "{{ key_data | from_json | json_query('privkey_4') }}"
- set_fact:
    pubkey_4:  "{{ key_data | from_json | json_query('pubkey_4') }}"
