

- set_fact:
    deb_url: "https://artifacts.elastic.co/downloads/beats/filebeat"
    deb_filename: "filebeat-oss-7.0.1-amd64.deb"

- name: Download Filebeat Deb
  get_url:
    url: "{{ deb_url }}/{{ deb_filename }}"
    dest: /tmp/{{ deb_filename }}
    force: no

# OS updates happening a bootup can block dpkg, use until
- name: Install Filebeat
  apt: deb="/tmp/{{ deb_filename }}"
  sudo: true
  register: apt_status
  until: apt_status|success
  delay: 6
  retries: 10

- name: Copy Filebeat Config
  become: true
  copy:
    dest: /etc/filebeat/filebeat.yml
    content: |
        logging.level: error
        filebeat.inputs:
        - type: log
          enabled: true
          json.keys_under_root: true
          json.add_error_key: true
          json.overwrite_keys: true
          overwrite_keys: true
          paths:
            - /home/admin/test-*/*.log
            - /home/admin/test-*/*.log.*

        output.elasticsearch:
          hosts:
            - "{{ elastic_url }}"
          protocol: "https"
          pipeline: timestamp_pipeline


- name: force systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: Start filebeat
  become: true
  systemd:
    state: restarted
    name: filebeat
