# This is pretty ugly, but it works.
# Ties together ips from secretmanager and kibana
# Relies on ec2.py and elastic_whitelist.py

- name: Apply elastic ip whitelist
  delegate_to: 127.0.0.1
  run_once: True
  shell: |
    echo "{{ elasticstack_data | to_nice_json(indent=2) }}" > elastic_whitelist_config.json
    ./ec2.py > ec2.json
    ../scripts/elastic_whitelist.py