# monit monitors and can restart processes

- name: Install monit
  command: sudo apt-get install monit
  become: true

- name: config -- coda-daemon
  become: true
  copy:
    dest: /etc/monit/conf.d/coda-daemon
    content: |
        CHECK PROCESS coda MATCHING "coda daemon"
            start program = "/home/admin/coda_start.sh"
                as uid "admin" and gid "admin"
            stop program = "/home/admin/scripts/stop-hard.sh"
                as uid "admin" and gid "admin"

- name: config -- monitrc
  become: true
  copy:
    dest: /etc/monit/monitrc
    content: |
        # Stripped down config
        set daemon 120            # check services at 2-minute intervals
        set logfile /var/log/monit.log
        set idfile /var/lib/monit/id
        set statefile /var/lib/monit/state
        set eventqueue
            basedir /var/lib/monit/events # set the base directory where events will be stored
            slots 100                     # optionally limit the queue size
        set httpd port 2812 and
            use address localhost  # only accept connection from localhost
            allow localhost        # allow localhost to connect to the server and
            allow admin:monit      # require user 'admin' with password 'monit'
        include /etc/monit/conf.d/*
        include /etc/monit/conf-enabled/*

- name: reload monit to get new config
  command: monit reload
  become: true
