---
- hosts: "tag_testnet_{{ netname }}"
  strategy: linear
  gather_facts: no
  vars:
    all_blockchain_lengths: |
      {%- set o=[] %}
      {%- for i in play_hosts %}
        {%- if o.append(hostvars[i].blockchain_length_fact) %}
        {%- endif %}
      {%- endfor %}
      {{ o }}
  tasks:
    - name: get block count
      shell: coda client status -json | jq .blockchain_length
      register: blockchain_length
    - set_fact:
        blockchain_length_fact: "{{ blockchain_length.stdout }}"


    - debug:
        var: all_blockchain_lengths
      run_once: true
      delegate_to: 127.0.0.1