---
- hosts: "tag_testnet_{{ netname }}"
  gather_facts: no
  run_once: True
  tasks:
    - include: tasks/task-secretmanager.yaml

- hosts: "tag_testnet_{{ netname }}"
  strategy: free
  gather_facts: no
  tasks:
    - include: tasks/task-wallet-keys.yaml
    - include: tasks/task-sshkeys.yaml
    - include: tasks/task-tools.yaml
    - include: tasks/task-offset.yaml
    - include: tasks/task-install-filebeat.yaml
    - include: tasks/task-install-metricbeat.yaml
    - include: tasks/task-testnet_config.yaml
    - include: tasks/task-install-carbon.yaml
    - include: tasks/task-status_graphite_cron.yaml

# Assign a unique ID to each blockproducer (so proof of stake works)
- hosts: "tag_role_{{ netname }}_blockproducer"
  gather_facts: no
  vars:
    id: "{{ ansible_play_hosts.index(inventory_hostname) }}"
  tasks:
    - name: Unique Proposer Priv Key
      copy:
        dest: /home/admin/wallet-keys/proposerkey
        mode: 0600
        content: "{{ lookup('vars', 'privkey_' + id) }}"
    - name: Unique Proposer Pub Key
      copy:
        dest: /home/admin/wallet-keys/proposerkey.pub
        mode: 0600
        content: "{{ lookup('vars', 'pubkey_' + id) }}"

- hosts: "tag_role_{{ netname }}_seed"
  gather_facts: no
  tasks:
    - include: tasks/task-testnetstats_cron.yaml