// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

var baseDir = "/usr/local/var/coda-network";

var keypairsDir = "/usr/local/var/coda-network/keypairs/";

var keysetsDir = "/usr/local/var/coda-network/keysets/";

function write(model, filename, contents) {
  var path = model ? keysetsDir + filename : keypairsDir + filename;
  try {
    Fs.writeFileSync(path, contents, "utf8");
    return /* () */0;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      var match = exn[1].message;
      if (match !== undefined) {
        console.log("Error: " + (String(match) + ""));
        return /* () */0;
      } else {
        console.log("An unknown error occured while writing a keypair to " + (String(filename) + ""));
        return /* () */0;
      }
    } else {
      throw exn;
    }
  }
}

exports.baseDir = baseDir;
exports.keypairsDir = keypairsDir;
exports.keysetsDir = keysetsDir;
exports.write = write;
/* fs Not a pure module */
