// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var baseDir = "/usr/local/var/coda-network";

var keypairsDir = "/usr/local/var/coda-network/keypairs/";

var keysetsDir = "/usr/local/var/coda-network/keysets/";

exports.baseDir = baseDir;
exports.keypairsDir = keypairsDir;
exports.keysetsDir = keysetsDir;
/* No side effect */
