// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Cmdliner = require("@elliottcable/bs-cmdliner/src/cmdliner.bs.js");
var Key$CodaNetwork = require("./Key.js");
var Keyset$CodaNetwork = require("./Keyset.js");

process.argv.shift()
;

function createKey(param) {
  console.log("Created key: " + Key$CodaNetwork.create(undefined).publicKey);
  return /* () */0;
}

var createKey_t = Cmdliner.Term.$(Cmdliner.Term.$$const(createKey), Cmdliner.Term.$$const(/* () */0));

function usage(param) {
  console.log("Please provide a COMMAND");
  return /* () */0;
}

var usage_t = Cmdliner.Term.$(Cmdliner.Term.$$const(usage), Cmdliner.Term.$$const(/* () */0));

function createKeyset(param) {
  Keyset$CodaNetwork.write(Keyset$CodaNetwork.create("testset"));
  return /* () */0;
}

var createKeyset_t = Cmdliner.Term.$(Cmdliner.Term.$$const(createKeyset), Cmdliner.Term.$$const(/* () */0));

var commands_000 = /* tuple */[
  createKey_t,
  Curry.app(Cmdliner.Term.info, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        "keypair"
      ])
];

var commands_001 = /* :: */[
  /* tuple */[
    createKeyset_t,
    Curry.app(Cmdliner.Term.info, [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          "keyset"
        ])
  ],
  /* [] */0
];

var commands = /* :: */[
  commands_000,
  commands_001
];

var arg = Cmdliner.Term.exit;

((function (eta) {
        return Curry._2(arg, undefined, eta);
      })(Cmdliner.Term.eval_choice(undefined, undefined, undefined, undefined, undefined, /* tuple */[
            usage_t,
            Curry.app(Cmdliner.Term.info, [
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  undefined,
                  "usage"
                ])
          ], commands)));

exports.createKey = createKey;
exports.createKey_t = createKey_t;
exports.usage = usage;
exports.usage_t = usage_t;
exports.createKeyset = createKeyset;
exports.createKeyset_t = createKeyset_t;
exports.commands = commands;
/*  Not a pure module */
