// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Config$CodaNetwork = require("./Config.js");
var CodaSDK$O1labsClientSdk = require("@o1labs/client-sdk/src/CodaSDK.bs.js");

function create(nickname) {
  var rawKeys = CodaSDK$O1labsClientSdk.genKeys(/* () */0);
  return {
          publicKey: rawKeys[/* publicKey */1],
          privateKey: rawKeys[/* privateKey */0],
          nickname: nickname
        };
}

function write(keypair) {
  var filename = Config$CodaNetwork.keypairsDir + Belt_Option.getWithDefault(keypair.nickname, keypair.publicKey);
  Fs.writeFileSync(filename, JSON.stringify(keypair), "utf8");
  return /* () */0;
}

var CodaSDK = 0;

exports.CodaSDK = CodaSDK;
exports.create = create;
exports.write = write;
/* fs Not a pure module */
