// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Cache$CodaNetwork = require("./Cache.js");
var Storage$CodaNetwork = require("./Storage.js");
var CodaSDK$O1labsClientSdk = require("@o1labs/client-sdk/src/CodaSDK.bs.js");

function filename(keypair) {
  return Belt_Option.getWithDefault(keypair.nickname, keypair.publicKey);
}

function create(nickname) {
  var keysRaw = CodaSDK$O1labsClientSdk.genKeys(undefined);
  return {
          publicKey: Belt_Option.getExn(Js_dict.get(keysRaw, "publicKey")),
          privateKey: Belt_Option.getExn(Js_dict.get(keysRaw, "privateKey")),
          nickname: nickname
        };
}

function write(keypair) {
  return Cache$CodaNetwork.write(/* Keypair */0, filename(keypair), JSON.stringify(keypair));
}

function uplaod(keypair) {
  Storage$CodaNetwork.upload(Storage$CodaNetwork.keypairBucket, filename(keypair));
  
}

var CodaSDK;

exports.CodaSDK = CodaSDK;
exports.filename = filename;
exports.create = create;
exports.write = write;
exports.uplaod = uplaod;
/* Cache-CodaNetwork Not a pure module */
