// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Storage = require("@google-cloud/storage");

var client = new $$Storage.Storage();

function upload(bucket, filename) {
  console.log("Upload started:", filename);
  return client.bucket(bucket).upload(filename).then((function (param) {
                  console.log("Upload successful!");
                  return Promise.resolve(undefined);
                })).catch((function (e) {
                var msg = e.message;
                if (msg !== undefined) {
                  console.log("Upload error:", msg);
                } else {
                  console.log("Unkown error while uploading file.");
                }
                return Promise.resolve(undefined);
              }));
}

function list(bucket, cb) {
  return client.bucket(bucket).getFiles(cb);
}

var keypairBucket = "network-keypairs";

var keysetBucket = "network-keysets";

exports.client = client;
exports.keypairBucket = keypairBucket;
exports.keysetBucket = keysetBucket;
exports.upload = upload;
exports.list = list;
/* client Not a pure module */
