// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Storage = require("@google-cloud/storage");

var client = new $$Storage.Storage();

function upload(bucket, filename, contents) {
  client.bucket(bucket).file(filename).save(contents, /* record */[/* resumable */false]);
  return /* () */0;
}

exports.client = client;
exports.upload = upload;
/* client Not a pure module */
